number_nicknames = {
    1: "Kelly's Eye number one",
    2: 'One Little Duck number two',
    3: 'Cup of Tea number three',
    4: 'Knock at the Door number four',
    5: 'Man Alive number five',
    6: 'Tom Mix number six',
    7: 'Lucky Seven number seven',
    8: 'Garden Gate number eight',
    9: "Doctor's Orders number nine",
    10: "Boris's Den number ten",
    11: 'Legs Eleven number eleven',
    12: 'One Dozen number twelve',
    13: 'Unlucky for Some number thirteen',
    14: "Valentine's Day number fourteen",
    15: 'Young and Keen number fifteen',
    16: 'Sweet Sixteen number sixteen',
    17: 'Dancing Queen number seventeen',
    18: 'Coming of Age number eighteen',
    19: 'Goodbye Teens number nineteen',
    20: 'One Score number twenty',
    21: 'Key of the Door number twenty one',
    22: 'Two Little Ducks number twenty two',
    23: 'Thee and Me number twenty three',
    24: 'Two Dozen number twenty four',
    25: 'Duck and Dive number twenty five',
    26: 'Half a Crown number twenty six',
    27: 'Gateway to Heaven number twenty seven',
    28: 'In a State number twenty eight',
    29: 'Rise and Shine number twenty nine',
    30: 'Dirty Gertie number thirty',
    31: 'Get Up and Run number thirty one',
    32: 'Buckle My Shoe number thirty two',
    33: 'All the Threes number thirty three',
    34: 'Ask for More number thirty four',
    35: 'Jump and Jive number thirty five',
    36: 'Three Dozen number thirty six',
    37: 'More than Eleven number thirty seven',
    38: 'Christmas Cake number thirty eight',
    39: 'Steps number thirty nine',
    40: 'Life Begins at Forty number forty',
    41: 'Time for Fun number forty one',
    42: 'Winnie the Pooh number forty two',
    43: 'Down on Your Knees number forty three',
    44: 'Droopy Drawers number forty four',
    45: 'Halfway There number forty five',
    46: 'Up to Tricks number forty six',
    47: 'Four and Seven number forty seven',
    48: 'Four Dozen number forty eight',
    49: 'PC number forty nine',
    50: 'Bullseye number fifty',
    51: 'Tweak of the Thumb number fifty one',
    52: 'Danny La Rue number fifty two',
    53: 'Here Comes Herbie number fifty three',
    54: 'Clean the Floor number fifty four',
    55: 'Snakes Alive number fifty five',
    56: 'Was She Worth It? number fifty six',
    57: 'Heinz Varieties number fifty seven',
    58: 'Make Them Wait number fifty eight',
    59: 'Brighton Line number fiftynine',
    60: 'Grandmas Getting Frisky number sixty',
    61: 'Bakers Bun number sixty one',
    62: 'Tickety Boo number sixty two',
    63: 'Tickle Me 63 number sixty three',
    64: 'Red Raw number sixty four',
    65: 'Old Age Pension number sixty five',
    66: 'Clickety Click number sixty six',
    67: 'Made in Heaven number sixty seven',
    68: 'Saving Grace number sixty eight',
    69: 'Either Way Up number sixty nine',
    70: 'Three Score and Ten number seventy',
    71: 'Bang on the Drum number seventy one',
    72: 'Six Dozen number seventy two',
    73: 'Queen B number seventy three',
    74: 'Candy Store number seventy four',
    75: 'Strive and Strive number seventy five',
    76: 'Trombones number seventy six',
    77: 'Sunset Strip number seventy seven',
    78: "Heaven's Gate number seventy eight",
    79: 'One More Time number seventy nine',
    80: "Gandhi's Breakfast number eighty",
    81: 'Stop and Run number eighty one',
    82: 'Straight on Through number eighty two',
    83: 'Time for Tea number eighty three',
    84: 'Seven Dozen number eighty four',
    85: 'Staying Alive number eighty five',
    86: 'Between the Sticks number eighty six',
    87: 'Torquay in Devon number eighty seven',
    88: 'Two Fat Ladies number eighty eight',
    89: 'Nearly There number eighty nine',
    90: 'Top of the Shop number ninety'

}
